# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rdt2_async_pb2 as rdt2__async__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rdt2_async_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RDT2AsyncInferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/rdt2.async_inference.RDT2AsyncInference/Health',
                request_serializer=rdt2__async__pb2.HealthRequest.SerializeToString,
                response_deserializer=rdt2__async__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/rdt2.async_inference.RDT2AsyncInference/Reset',
                request_serializer=rdt2__async__pb2.ResetRequest.SerializeToString,
                response_deserializer=rdt2__async__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.SubmitObservation = channel.unary_unary(
                '/rdt2.async_inference.RDT2AsyncInference/SubmitObservation',
                request_serializer=rdt2__async__pb2.ObservationRequest.SerializeToString,
                response_deserializer=rdt2__async__pb2.ObservationAck.FromString,
                _registered_method=True)
        self.StreamActions = channel.unary_stream(
                '/rdt2.async_inference.RDT2AsyncInference/StreamActions',
                request_serializer=rdt2__async__pb2.ActionStreamRequest.SerializeToString,
                response_deserializer=rdt2__async__pb2.ActionChunk.FromString,
                _registered_method=True)


class RDT2AsyncInferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RDT2AsyncInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=rdt2__async__pb2.HealthRequest.FromString,
                    response_serializer=rdt2__async__pb2.HealthResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=rdt2__async__pb2.ResetRequest.FromString,
                    response_serializer=rdt2__async__pb2.ResetResponse.SerializeToString,
            ),
            'SubmitObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitObservation,
                    request_deserializer=rdt2__async__pb2.ObservationRequest.FromString,
                    response_serializer=rdt2__async__pb2.ObservationAck.SerializeToString,
            ),
            'StreamActions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamActions,
                    request_deserializer=rdt2__async__pb2.ActionStreamRequest.FromString,
                    response_serializer=rdt2__async__pb2.ActionChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rdt2.async_inference.RDT2AsyncInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rdt2.async_inference.RDT2AsyncInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RDT2AsyncInference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdt2.async_inference.RDT2AsyncInference/Health',
            rdt2__async__pb2.HealthRequest.SerializeToString,
            rdt2__async__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdt2.async_inference.RDT2AsyncInference/Reset',
            rdt2__async__pb2.ResetRequest.SerializeToString,
            rdt2__async__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdt2.async_inference.RDT2AsyncInference/SubmitObservation',
            rdt2__async__pb2.ObservationRequest.SerializeToString,
            rdt2__async__pb2.ObservationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rdt2.async_inference.RDT2AsyncInference/StreamActions',
            rdt2__async__pb2.ActionStreamRequest.SerializeToString,
            rdt2__async__pb2.ActionChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
