# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rdt2_async.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rdt2_async.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rdt2_async.proto\x12\x14rdt2.async_inference\"\x0f\n\rHealthRequest\"0\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0e\n\x0cResetRequest\",\n\rResetResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xcd\x01\n\x12ObservationRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x03\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x13\n\x0binstruction\x18\x03 \x01(\t\x12\x18\n\x10left_stereo_jpeg\x18\x04 \x01(\x0c\x12\x19\n\x11right_stereo_jpeg\x18\x05 \x01(\x0c\x12\r\n\x05state\x18\x06 \x03(\x02\x12\x15\n\rtcp_pose_flat\x18\x07 \x03(\x02\x12 \n\x18latest_executed_timestep\x18\x08 \x01(\x03\"G\n\x0eObservationAck\x12\x12\n\nrequest_id\x18\x01 \x01(\x03\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x15\n\x13\x41\x63tionStreamRequest\"\xbb\x01\n\x0b\x41\x63tionChunk\x12\x12\n\nrequest_id\x18\x01 \x01(\x03\x12\x19\n\x11\x63reated_timestamp\x18\x02 \x01(\x01\x12\x13\n\x0b\x61\x63tion_flat\x18\x03 \x03(\x02\x12\x0f\n\x07horizon\x18\x04 \x01(\x05\x12\x12\n\naction_dim\x18\x05 \x01(\x05\x12\x1c\n\x14inference_latency_ms\x18\x06 \x01(\x01\x12\r\n\x05\x65rror\x18\x07 \x01(\t\x12\x16\n\x0e\x66irst_timestep\x18\x08 \x01(\x03\x32\x81\x03\n\x12RDT2AsyncInference\x12S\n\x06Health\x12#.rdt2.async_inference.HealthRequest\x1a$.rdt2.async_inference.HealthResponse\x12P\n\x05Reset\x12\".rdt2.async_inference.ResetRequest\x1a#.rdt2.async_inference.ResetResponse\x12\x63\n\x11SubmitObservation\x12(.rdt2.async_inference.ObservationRequest\x1a$.rdt2.async_inference.ObservationAck\x12_\n\rStreamActions\x12).rdt2.async_inference.ActionStreamRequest\x1a!.rdt2.async_inference.ActionChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rdt2_async_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=42
  _globals['_HEALTHREQUEST']._serialized_end=57
  _globals['_HEALTHRESPONSE']._serialized_start=59
  _globals['_HEALTHRESPONSE']._serialized_end=107
  _globals['_RESETREQUEST']._serialized_start=109
  _globals['_RESETREQUEST']._serialized_end=123
  _globals['_RESETRESPONSE']._serialized_start=125
  _globals['_RESETRESPONSE']._serialized_end=169
  _globals['_OBSERVATIONREQUEST']._serialized_start=172
  _globals['_OBSERVATIONREQUEST']._serialized_end=377
  _globals['_OBSERVATIONACK']._serialized_start=379
  _globals['_OBSERVATIONACK']._serialized_end=450
  _globals['_ACTIONSTREAMREQUEST']._serialized_start=452
  _globals['_ACTIONSTREAMREQUEST']._serialized_end=473
  _globals['_ACTIONCHUNK']._serialized_start=476
  _globals['_ACTIONCHUNK']._serialized_end=663
  _globals['_RDT2ASYNCINFERENCE']._serialized_start=666
  _globals['_RDT2ASYNCINFERENCE']._serialized_end=1051
# @@protoc_insertion_point(module_scope)
